project:
  type: website

website:
  title: "Linear_Mixed_Effect_Models_2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: example_1.qmd
        text: 'Example #1'
      - href: example_2.qmd
        text: 'Example #2'
      - href: example_3.qmd
        text: 'Example #3'



format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

