project:
  type: website

website:
  title: "Linear_Mixed_Effect_Models_2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: example_1.qmd
        text: 'Example #1'


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

