project:
  type: website

website:
  title: "Linear_Mixed_Effect_Models_2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example_1.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

