<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Linear_Mixed_Effect_Models_2 - Example #2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Linear_Mixed_Effect_Models_2</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./example_1.html" rel="" target="">
 <span class="menu-text">Example #1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./example_2.html" rel="" target="" aria-current="page">
 <span class="menu-text">Example #2</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#example-2" id="toc-example-2" class="nav-link" data-scroll-target="#example-2">Example #2</a>
  <ul class="collapse">
  <li><a href="#first-look-at-the-data" id="toc-first-look-at-the-data" class="nav-link" data-scroll-target="#first-look-at-the-data">First look at the data</a></li>
  <li><a href="#variable-meanings" id="toc-variable-meanings" class="nav-link" data-scroll-target="#variable-meanings">Variable Meanings</a></li>
  <li><a href="#no-predictor-model" id="toc-no-predictor-model" class="nav-link" data-scroll-target="#no-predictor-model">No predictor model</a></li>
  <li><a href="#first-model-with-predictors-fixed-and-random-effects" id="toc-first-model-with-predictors-fixed-and-random-effects" class="nav-link" data-scroll-target="#first-model-with-predictors-fixed-and-random-effects">First model with predictors: fixed and random effects</a></li>
  <li><a href="#compare-baseline-and-first-model" id="toc-compare-baseline-and-first-model" class="nav-link" data-scroll-target="#compare-baseline-and-first-model">Compare baseline and first model</a></li>
  <li><a href="#a-better-model-lets-see" id="toc-a-better-model-lets-see" class="nav-link" data-scroll-target="#a-better-model-lets-see">A better model? Let’s see</a></li>
  </ul></li>
  <li><a href="#what-about-a-regular-linear-models" id="toc-what-about-a-regular-linear-models" class="nav-link" data-scroll-target="#what-about-a-regular-linear-models">What about a regular linear models</a>
  <ul class="collapse">
  <li><a href="#predictor" id="toc-predictor" class="nav-link" data-scroll-target="#predictor">1 Predictor</a></li>
  <li><a href="#predictors" id="toc-predictors" class="nav-link" data-scroll-target="#predictors">2 Predictors</a></li>
  <li><a href="#down-the-rabbit-hole" id="toc-down-the-rabbit-hole" class="nav-link" data-scroll-target="#down-the-rabbit-hole">Down the rabbit hole</a></li>
  <li><a href="#compare-models" id="toc-compare-models" class="nav-link" data-scroll-target="#compare-models">Compare models</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Example #2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Compare models with fresh data</p>
</section>
<section id="example-2" class="level2">
<h2 class="anchored" data-anchor-id="example-2">Example #2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(flexplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: flexplot</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lme4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: dplyr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ggplot2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:flexplot':

    flip_data</code></pre>
</div>
</div>
<section id="first-look-at-the-data" class="level3">
<h3 class="anchored" data-anchor-id="first-look-at-the-data">First look at the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(math)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(math,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   School Minority    Sex    SES MathAch MEANSES
1    1224       No Female -1.528   5.876  -0.428
2    1224       No Female -0.588  19.708  -0.428
3    1224       No   Male -0.528  20.349  -0.428
4    1224       No   Male -0.668   8.781  -0.428
5    1224       No   Male -0.158  17.898  -0.428
6    1224       No   Male  0.022   4.583  -0.428
7    1224       No Female -0.618  -2.832  -0.428
8    1224       No   Male -0.998   0.523  -0.428
9    1224       No Female -0.888   1.527  -0.428
10   1224       No   Male -0.458  21.521  -0.428</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(math)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 7,185
Columns: 6
$ School   &lt;int&gt; 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1…
$ Minority &lt;fct&gt; No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…
$ Sex      &lt;fct&gt; Female, Female, Male, Male, Male, Male, Female, Male, Female,…
$ SES      &lt;dbl&gt; -1.528, -0.588, -0.528, -0.668, -0.158, 0.022, -0.618, -0.998…
$ MathAch  &lt;dbl&gt; 5.876, 19.708, 20.349, 8.781, 17.898, 4.583, -2.832, 0.523, 1…
$ MEANSES  &lt;dbl&gt; -0.428, -0.428, -0.428, -0.428, -0.428, -0.428, -0.428, -0.42…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>math <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Minority, Sex) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">.groups =</span> <span class="st">"keep"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
# Groups:   Minority, Sex [4]
  Minority Sex   
  &lt;fct&gt;    &lt;fct&gt; 
1 No       Female
2 No       Male  
3 Yes      Female
4 Yes      Male  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>math <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(School) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">.groups =</span> <span class="st">"keep"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 160 × 1
# Groups:   School [160]
   School
    &lt;int&gt;
 1   1224
 2   1288
 3   1296
 4   1308
 5   1317
 6   1358
 7   1374
 8   1433
 9   1436
10   1461
# ℹ 150 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(math)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     School     Minority       Sex            SES               MathAch      
 Min.   :1224   No :5211   Female:3795   Min.   :-3.758000   Min.   :-2.832  
 1st Qu.:3020   Yes:1974   Male  :3390   1st Qu.:-0.538000   1st Qu.: 7.275  
 Median :5192                            Median : 0.002000   Median :13.131  
 Mean   :5278                            Mean   : 0.000143   Mean   :12.748  
 3rd Qu.:7342                            3rd Qu.: 0.602000   3rd Qu.:18.317  
 Max.   :9586                            Max.   : 2.692000   Max.   :24.993  
    MEANSES         
 Min.   :-1.188000  
 1st Qu.:-0.317000  
 Median : 0.038000  
 Mean   : 0.006138  
 3rd Qu.: 0.333000  
 Max.   : 0.831000  </code></pre>
</div>
</div>
<section id="comments" class="level4">
<h4 class="anchored" data-anchor-id="comments">Comments</h4>
<ul>
<li><p>From the above, we have 160 schools with two genders classified as minority or not.</p></li>
<li><p>SES and MEANSES look like distributions centered around 0</p></li>
<li><p>MathAch is centered around ~13 and has -ve scores! Curious how one can attain a negative achievement score in Math: must be somehow a normalized variable.</p></li>
<li><p>Do some plots to look more closely at distributions</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plots </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(math, <span class="fu">aes</span>(MathAch)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(math, <span class="fu">aes</span>(SES)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(math, <span class="fu">aes</span>(MEANSES)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="variable-meanings" class="level3">
<h3 class="anchored" data-anchor-id="variable-meanings">Variable Meanings</h3>
<ul>
<li><p>SES is Socio-Economic Status or Score?</p></li>
<li><p>MEANSES is ?</p></li>
<li><p>MathAch is achievement in Math?</p></li>
</ul>
</section>
<section id="no-predictor-model" class="level3">
<h3 class="anchored" data-anchor-id="no-predictor-model">No predictor model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># no predictor</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>mod_baseline <span class="ot">&lt;-</span> <span class="fu">lmer</span>(MathAch<span class="sc">~</span><span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>School), <span class="at">data=</span>math)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(mod_baseline, <span class="at">plot =</span> <span class="st">"model"</span>, <span class="at">sample =</span> <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Coordinate system already present. Adding new coordinate system, which will
replace the existing one.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_baseline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: MathAch ~ 1 + (1 | School)
   Data: math

REML criterion at convergence: 47116.8

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.0631 -0.7539  0.0267  0.7606  2.7426 

Random effects:
 Groups   Name        Variance Std.Dev.
 School   (Intercept)  8.614   2.935   
 Residual             39.148   6.257   
Number of obs: 7185, groups:  School, 160

Fixed effects:
            Estimate Std. Error t value
(Intercept)  12.6370     0.2444   51.71</code></pre>
</div>
</div>
</section>
<section id="first-model-with-predictors-fixed-and-random-effects" class="level3">
<h3 class="anchored" data-anchor-id="first-model-with-predictors-fixed-and-random-effects">First model with predictors: fixed and random effects</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SES as fixed and random effect</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>mod_ses <span class="ot">&lt;-</span> <span class="fu">lmer</span>(MathAch<span class="sc">~</span>SES <span class="sc">+</span> (SES<span class="sc">|</span>School), <span class="at">data=</span>math)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(mod_ses, <span class="at">plot =</span> <span class="st">"model"</span>, <span class="at">sample =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_ses)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: MathAch ~ SES + (SES | School)
   Data: math

REML criterion at convergence: 46640.4

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-3.12272 -0.73046  0.02144  0.75610  2.94356 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 School   (Intercept)  4.8287  2.1974        
          SES          0.4129  0.6426   -0.11
 Residual             36.8301  6.0688        
Number of obs: 7185, groups:  School, 160

Fixed effects:
            Estimate Std. Error t value
(Intercept)  12.6650     0.1898   66.71
SES           2.3938     0.1181   20.27

Correlation of Fixed Effects:
    (Intr)
SES -0.045</code></pre>
</div>
</div>
<section id="comments-1" class="level4">
<h4 class="anchored" data-anchor-id="comments-1">Comments</h4>
<p>Fixed effect is very clear with individual schools being close to parallel to fixed effect</p>
</section>
</section>
<section id="compare-baseline-and-first-model" class="level3">
<h3 class="anchored" data-anchor-id="compare-baseline-and-first-model">Compare baseline and first model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare models</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model.comparison</span>(mod_baseline, mod_ses)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>refitting model(s) with ML (instead of REML)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$statistics
                  aic      bic bayes.factor      p
mod_baseline 47122.79 47143.43 0.000000e+00 &lt;2e-16
mod_ses      46652.40 46693.68 4.605423e+97       

$predicted_differences
   0%   25%   50%   75%  100% 
0.000 0.514 1.071 1.802 8.991 

$r_squared_change
   Residual (Intercept) 
 0.05921519  0.43943350 </code></pre>
</div>
</div>
<section id="comments-2" class="level4">
<h4 class="anchored" data-anchor-id="comments-2">Comments</h4>
<ul>
<li><p>Bayes Factor favors mod_ses and great p value</p></li>
<li><p>R^2 change (by using mod_ses that has SES predictor):</p>
<ul>
<li><p>explains 5.92 % of the residual variance. Difference between fitted models for each cluster (in this case, each school).</p></li>
<li><p>43.94 % of variance in intercept (relative to the mod_base that has no predictor - juts the mean of every data point)</p></li>
</ul></li>
<li><p>Visualize that….</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># see the difference with 3 example schools</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">compare.fits</span>(MathAch<span class="sc">~</span>SES <span class="sc">|</span> School, mod_baseline, mod_ses, <span class="at">data =</span> math)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-3" class="level4">
<h4 class="anchored" data-anchor-id="comments-3">Comments</h4>
<ul>
<li><p>Plots are narrow</p></li>
<li><p>sample=n is not observed</p></li>
</ul>
</section>
</section>
<section id="a-better-model-lets-see" class="level3">
<h3 class="anchored" data-anchor-id="a-better-model-lets-see">A better model? Let’s see</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a better model including Minority?</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>mod_ses_minority <span class="ot">&lt;-</span> <span class="fu">lmer</span>(MathAch<span class="sc">~</span>SES <span class="sc">+</span> Minority <span class="sc">+</span> (SES<span class="sc">|</span>School), <span class="at">data=</span>math)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(mod_ses_minority, <span class="at">plot =</span> <span class="st">"model"</span>, <span class="at">sample =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_ses_minority)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: MathAch ~ SES + Minority + (SES | School)
   Data: math

REML criterion at convergence: 46443

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.1742 -0.7243  0.0283  0.7577  3.0047 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 School   (Intercept)  3.9362  1.9840        
          SES          0.3187  0.5645   -0.40
 Residual             35.9967  5.9997        
Number of obs: 7185, groups:  School, 160

Fixed effects:
            Estimate Std. Error t value
(Intercept)  13.5047     0.1827   73.92
SES           2.1326     0.1156   18.44
MinorityYes  -2.9782     0.2081  -14.31

Correlation of Fixed Effects:
            (Intr) SES   
SES         -0.194       
MinorityYes -0.307  0.173</code></pre>
</div>
</div>
<ul>
<li>Compare …</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># better model?</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># compare models</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">model.comparison</span>(mod_baseline, mod_ses_minority)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>refitting model(s) with ML (instead of REML)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$statistics
                      aic      bic  bayes.factor      p
mod_baseline     47122.79 47143.43  0.000000e+00 &lt;2e-16
mod_ses_minority 46457.03 46505.19 3.917437e+138       

$predicted_differences
   0%   25%   50%   75%  100% 
0.000 0.564 1.187 2.028 7.690 

$r_squared_change
   Residual (Intercept) 
 0.08050517  0.54305152 </code></pre>
</div>
</div>
<ul>
<li><p>Bayes Factor is much better: 3.917437e+138 vs 4.605423e+97</p></li>
<li><p>R^2 change (by using mod_ses_minority that has SES and Minority predictors):</p>
<ul>
<li><p>explains 8.05 % of the residual variance. Difference between fitted models for each cluster (in this case, each school) vs ~6%</p></li>
<li><p>54.31 % of variance in intercept (relative to the mod_base that has no predictor - just the mean of every data point)</p></li>
</ul></li>
<li><p>Visualize that….</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># see the difference with 3 example schools</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">compare.fits</span>(MathAch<span class="sc">~</span>SES <span class="sc">|</span> Minority <span class="sc">+</span> School, mod_baseline, mod_ses_minority, <span class="at">data =</span> math)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="what-about-a-regular-linear-models" class="level2">
<h2 class="anchored" data-anchor-id="what-about-a-regular-linear-models">What about a regular linear models</h2>
<ul>
<li>some additional ggplots will help with understanding variables</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># it's a factor</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>math<span class="sc">$</span>School <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(math<span class="sc">$</span>School)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="predictor" class="level3">
<h3 class="anchored" data-anchor-id="predictor">1 Predictor</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SES with Minority colouring</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(math, <span class="fu">aes</span>(<span class="at">x=</span>SES, <span class="at">y=</span>MathAch, <span class="at">colour=</span>Minority)) <span class="sc">+</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> <span class="st">'y ~ x'</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model 1 factor </span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MathAch <span class="sc">~</span> SES, <span class="at">data =</span> math)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MathAch ~ SES, data = math)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.4382  -4.7580   0.2334   5.0649  15.9007 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 12.74740    0.07569  168.42   &lt;2e-16 ***
SES          3.18387    0.09712   32.78   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.416 on 7183 degrees of freedom
Multiple R-squared:  0.1301,    Adjusted R-squared:   0.13 
F-statistic:  1075 on 1 and 7183 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(lm1, <span class="at">plot=</span><span class="st">"model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(lm1, <span class="at">plot=</span><span class="st">"residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="comments-4" class="level4">
<h4 class="anchored" data-anchor-id="comments-4">Comments</h4>
<ul>
<li><p>It’s not obvious from the scatter-plot points that SES will be a good predictor - though regression line with SE shows the correlation.</p></li>
<li><p>MinorityYes points can be seen emerging in bottom left - less SES ~ less MathAch</p></li>
<li><p>SES is highly significant though the Adjusted R-squared is small (0.13)</p></li>
</ul>
</section>
</section>
<section id="predictors" class="level3">
<h3 class="anchored" data-anchor-id="predictors">2 Predictors</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Belt and braces: Minority box and violin</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(math, <span class="fu">aes</span>(<span class="at">x=</span>Minority, <span class="at">y=</span>MathAch, <span class="at">colour=</span>Minority)) <span class="sc">+</span> </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span> </span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">shape=</span><span class="dv">16</span>, <span class="at">position=</span><span class="fu">position_jitter</span>(<span class="fl">0.4</span>), <span class="at">size=</span><span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.1</span>, <span class="at">colour=</span><span class="st">"black"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 factors</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MathAch <span class="sc">~</span> SES <span class="sc">+</span> Minority, <span class="at">data =</span> math)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MathAch ~ SES + Minority, data = math)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.6824  -4.6338   0.2277   4.9502  17.1271 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13.52473    0.08822  153.31   &lt;2e-16 ***
SES          2.74398    0.09909   27.69   &lt;2e-16 ***
MinorityYes -2.82912    0.17299  -16.35   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.3 on 7182 degrees of freedom
Multiple R-squared:  0.1614,    Adjusted R-squared:  0.1611 
F-statistic:   691 on 2 and 7182 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(lm2, <span class="at">plot=</span><span class="st">"model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(lm2, <span class="at">plot=</span><span class="st">"residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="example_2_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="comments-5" class="level4">
<h4 class="anchored" data-anchor-id="comments-5">Comments</h4>
<ul>
<li><p>Box Violin plot show clearly the effect of Minority</p></li>
<li><p>Median is about 5 points down for Yes</p></li>
</ul>
</section>
</section>
<section id="down-the-rabbit-hole" class="level3">
<h3 class="anchored" data-anchor-id="down-the-rabbit-hole">Down the rabbit hole</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># interesting </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># what does this mean?</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>lm3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MathAch <span class="sc">~</span> SES <span class="sc">+</span> Minority <span class="sc">+</span> School, <span class="at">data =</span> math)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MathAch ~ SES + Minority + School, data = math)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.9965  -4.3088   0.1334   4.4711  18.2567 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 10.81000    0.87795  12.313  &lt; 2e-16 ***
SES          1.95248    0.10886  17.935  &lt; 2e-16 ***
MinorityYes -2.89558    0.22012 -13.155  &lt; 2e-16 ***
School1288   2.81085    1.48902   1.888 0.059104 .  
School1296   0.49199    1.24892   0.394 0.693640    
School1308   5.57282    1.61018   3.461 0.000541 ***
School1317   3.80479    1.24592   3.054 0.002268 ** 
School1358   0.72419    1.40520   0.515 0.606316    
School1374  -0.12613    1.43670  -0.088 0.930045    
School1433   7.60171    1.34748   5.641 1.75e-08 ***
School1436   6.20255    1.26525   4.902 9.69e-07 ***
School1461   4.79767    1.37016   3.502 0.000465 ***
School1462   3.83734    1.20007   3.198 0.001392 ** 
School1477   3.24700    1.16411   2.789 0.005297 ** 
School1499  -0.98336    1.20658  -0.815 0.415098    
School1637  -0.37097    1.45751  -0.255 0.799100    
School1906   4.44741    1.20859   3.680 0.000235 ***
School1909   3.12897    1.43663   2.178 0.029440 *  
School1942   6.06915    1.42424   4.261 2.06e-05 ***
School1946   2.38751    1.30269   1.833 0.066882 .  
School2030   0.81185    1.24249   0.653 0.513516    
School2208   3.76844    1.17430   3.209 0.001338 ** 
School2277   2.20629    1.17595   1.876 0.060674 .  
School2305   4.31984    1.15904   3.727 0.000195 ***
School2336   4.90714    1.24332   3.947 8.00e-05 ***
School2458   4.50892    1.19320   3.779 0.000159 ***
School2467  -0.01869    1.20976  -0.015 0.987673    
School2526   5.65551    1.18695   4.765 1.93e-06 ***
School2626   2.71321    1.31177   2.068 0.038643 *  
School2629   4.97612    1.18502   4.199 2.71e-05 ***
School2639   0.58408    1.29171   0.452 0.651155    
School2651   0.30360    1.31220   0.231 0.817034    
School2655   5.24387    1.21972   4.299 1.74e-05 ***
School2658   2.30922    1.25763   1.836 0.066375 .  
School2755   5.62819    1.24681   4.514 6.46e-06 ***
School2768   0.41322    1.48829   0.278 0.781292    
School2771   1.74953    1.19394   1.465 0.142873    
School2818   2.91961    1.27746   2.285 0.022315 *  
School2917   1.42105    1.28149   1.109 0.267510    
School2990   8.29000    1.24760   6.645 3.26e-11 ***
School2995  -0.10831    1.24685  -0.087 0.930778    
School3013   1.94181    1.20491   1.612 0.107098    
School3020   3.23409    1.17720   2.747 0.006024 ** 
School3039   6.57803    1.58172   4.159 3.24e-05 ***
School3088   0.96627    1.30646   0.740 0.459565    
School3152   2.56117    1.21064   2.116 0.034418 *  
School3332   2.27427    1.31591   1.728 0.083981 .  
School3351   0.83517    1.30559   0.640 0.522396    
School3377   2.15776    1.26629   1.704 0.088426 .  
School3427   8.96138    1.22881   7.293 3.37e-13 ***
School3498   4.51124    1.21000   3.728 0.000194 ***
School3499   2.88351    1.31803   2.188 0.028721 *  
School3533   1.00773    1.23591   0.815 0.414885    
School3610   5.17004    1.15742   4.467 8.06e-06 ***
School3657   0.03545    1.21557   0.029 0.976734    
School3688   3.12280    1.27146   2.456 0.014071 *  
School3705   0.54347    1.25997   0.431 0.666239    
School3716   2.00438    1.28860   1.555 0.119880    
School3838   6.14873    1.20328   5.110 3.31e-07 ***
School3881   1.17256    1.28580   0.912 0.361836    
School3967   1.66461    1.20989   1.376 0.168918    
School3992   4.37835    1.21067   3.616 0.000301 ***
School3999   2.20023    1.25389   1.755 0.079351 .  
School4042   2.72052    1.15799   2.349 0.018834 *  
School4173   2.04960    1.26172   1.624 0.104324    
School4223   4.25354    1.25401   3.392 0.000698 ***
School4253   2.12821    1.19553   1.780 0.075095 .  
School4292   5.32002    1.16133   4.581 4.71e-06 ***
School4325   2.68983    1.20487   2.232 0.025616 *  
School4350   1.44942    1.36713   1.060 0.289095    
School4383   1.20770    1.48934   0.811 0.417454    
School4410   2.54540    1.28559   1.980 0.047748 *  
School4420   3.50200    1.37767   2.542 0.011044 *  
School4458  -0.65723    1.24346  -0.529 0.597136    
School4511   3.10776    1.18008   2.634 0.008469 ** 
School4523   0.48065    1.25703   0.382 0.702198    
School4530   0.65207    1.16078   0.562 0.574303    
School4642   3.65857    1.16795   3.132 0.001741 ** 
School4868   2.07256    1.35895   1.525 0.127274    
School4931   2.41840    1.18265   2.045 0.040902 *  
School5192   0.44779    1.43594   0.312 0.755166    
School5404   3.14662    1.19193   2.640 0.008311 ** 
School5619   3.78555    1.15074   3.290 0.001008 ** 
School5640   2.69490    1.18454   2.275 0.022933 *  
School5650   5.99356    1.26802   4.727 2.33e-06 ***
School5667   2.52979    1.17033   2.162 0.030682 *  
School5720   3.40872    1.20525   2.828 0.004694 ** 
School5761   2.18376    1.21206   1.802 0.071637 .  
School5762  -1.57144    1.33349  -1.178 0.238660    
School5783   2.70143    1.42138   1.901 0.057399 .  
School5815  -1.05273    1.48936  -0.707 0.479695    
School5819   1.09015    1.22281   0.892 0.372685    
School5838   2.66742    1.39200   1.916 0.055374 .  
School5937   4.79482    1.42396   3.367 0.000763 ***
School6074   3.61285    1.18905   3.038 0.002387 ** 
School6089   4.59178    1.36611   3.361 0.000780 ***
School6144  -0.73726    1.26868  -0.581 0.561173    
School6170   4.64975    1.57797   2.947 0.003223 ** 
School6291   2.46695    1.34948   1.828 0.067580 .  
School6366   4.64099    1.18248   3.925 8.76e-05 ***
School6397   3.32574    1.17220   2.837 0.004565 ** 
School6415   1.52307    1.19922   1.270 0.204110    
School6443   0.41647    1.40591   0.296 0.767066    
School6464   0.49761    1.43300   0.347 0.728412    
School6469   7.34482    1.19449   6.149 8.23e-10 ***
School6484   2.62935    1.34209   1.959 0.050136 .  
School6578   2.76137    1.18916   2.322 0.020255 *  
School6600   1.10183    1.18961   0.926 0.354369    
School6808   0.04589    1.26462   0.036 0.971056    
School6816   5.01202    1.21099   4.139 3.53e-05 ***
School6897   4.13698    1.23045   3.362 0.000777 ***
School6990  -0.98150    1.22074  -0.804 0.421409    
School7011   3.06475    1.36566   2.244 0.024854 *  
School7101   1.75016    1.43621   1.219 0.223040    
School7172   0.52084    1.27490   0.409 0.682896    
School7232   2.24269    1.21022   1.853 0.063908 .  
School7276   2.48153    1.20640   2.057 0.039726 *  
School7332   3.66849    1.23607   2.968 0.003009 ** 
School7341  -0.01415    1.21615  -0.012 0.990715    
School7342   2.27919    1.18108   1.930 0.053678 .  
School7345   1.23923    1.19096   1.041 0.298128    
School7364   3.60242    1.26128   2.856 0.004301 ** 
School7635   3.78111    1.21740   3.106 0.001905 ** 
School7688   7.51748    1.20083   6.260 4.07e-10 ***
School7697   4.40755    1.37942   3.195 0.001403 ** 
School7734   1.85061    1.55413   1.191 0.233783    
School7890  -1.16445    1.21525  -0.958 0.337993    
School7919   3.22463    1.32435   2.435 0.014921 *  
School8009   3.25372    1.24611   2.611 0.009044 ** 
School8150   3.70841    1.26330   2.935 0.003341 ** 
School8165   5.21531    1.22966   4.241 2.25e-05 ***
School8175   3.06585    1.37103   2.236 0.025373 *  
School8188   2.14217    1.40609   1.523 0.127680    
School8193   6.50780    1.26927   5.127 3.02e-07 ***
School8202   1.23146    1.34329   0.917 0.359305    
School8357   3.88852    1.45173   2.679 0.007412 ** 
School8367  -5.89349    1.83067  -3.219 0.001291 ** 
School8477   2.48643    1.32121   1.882 0.059886 .  
School8531   2.48687    1.28810   1.931 0.053567 .  
School8627   0.36074    1.20589   0.299 0.764836    
School8628   5.99134    1.16697   5.134 2.91e-07 ***
School8707   2.67593    1.23640   2.164 0.030476 *  
School8775   0.04408    1.23391   0.036 0.971501    
School8800   0.08242    1.38495   0.060 0.952549    
School8854  -4.54976    1.37794  -3.302 0.000965 ***
School8857   5.64889    1.17050   4.826 1.42e-06 ***
School8874   2.95601    1.33260   2.218 0.026571 *  
School8946   0.40105    1.17956   0.340 0.733867    
School8983   0.81257    1.21536   0.669 0.503782    
School9021   2.97339    1.19459   2.489 0.012832 *  
School9104   4.57053    1.20051   3.807 0.000142 ***
School9158  -0.66014    1.20498  -0.548 0.583817    
School9198   7.32167    1.39411   5.252 1.55e-07 ***
School9225   3.60389    1.33320   2.703 0.006884 ** 
School9292   3.52560    1.64597   2.142 0.032231 *  
School9340   1.14429    1.41928   0.806 0.420128    
School9347   2.56951    1.18623   2.166 0.030336 *  
School9359   3.87856    1.20714   3.213 0.001319 ** 
School9397  -0.34677    1.24142  -0.279 0.779999    
School9508   3.61321    1.34255   2.691 0.007134 ** 
School9550   0.77467    1.42057   0.545 0.585546    
School9586   2.98814    1.18054   2.531 0.011390 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.01 on 7023 degrees of freedom
Multiple R-squared:  0.2536,    Adjusted R-squared:  0.2365 
F-statistic: 14.82 on 161 and 7023 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="comments-6" class="level4">
<h4 class="anchored" data-anchor-id="comments-6">Comments</h4>
<ul>
<li>Does this mean that the model with SES + Minority is better for some schools</li>
</ul>
</section>
</section>
<section id="compare-models" class="level3">
<h3 class="anchored" data-anchor-id="compare-models">Compare models</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare standard 1 and 2 predictor models</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model.comparison</span>(lm1, lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$statistics
         aic      bic bayes.factor      p   rsq
lm1 47103.94 47124.58 0.000000e+00 &lt;2e-16 0.130
lm2 46843.23 46870.75 1.312994e+55        0.161

$predicted_differences
   0%   25%   50%   75%  100% 
0.051 0.565 0.886 1.472 3.236 </code></pre>
</div>
</div>
<section id="comments-7" class="level4">
<h4 class="anchored" data-anchor-id="comments-7">Comments</h4>
<ul>
<li>lm2 better than 1</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the standard 2 predictor model with the MM with 2 predictors </span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model.comparison</span>(lm2, mod_ses_minority)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$statistics
                      aic      bic bayes.factor
lm2              46843.23 46870.75 0.000000e+00
mod_ses_minority 46457.03 46505.19 2.402547e+79

$predicted_differences
   0%   25%   50%   75%  100% 
0.000 0.495 1.097 1.965 7.403 </code></pre>
</div>
</div>
</section>
<section id="comments-8" class="level4">
<h4 class="anchored" data-anchor-id="comments-8">Comments</h4>
<ul>
<li>MM better than standard 2 predictor variable model?</li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>